database:
  sql:
    type: SQLITE

    SQLITE:
      auto-commit: true
      valid-timeout: 60000

    MYSQL:
      host: 127.0.0.1:3306
      database: minecraft
      username: root
      password: 1234
      max-pool-size: 10